### ISSUE TITLE
Ability to turn on panda's or groupings at a specific time

### ISSUE THREAD

**Issue by JohnnyRS** [JohnnyRS/PandaCrazy-Max#11]
I think this would be great to have as a new feature.

**Comment by JohnnyRS** [comment]
I added a data for starting and ending groupings at a specific time. Just need to let users change this data and figure out how to get this to work properly.

**Comment by JohnnyRS** [comment]
This has been finished and now can start a group at a specific time each day for a specified amount of hours and minutes. This is the only way to start panda's automatically. I went with this option because it's easier to check groups than each panda. Thinking about a turn off option for weekends.

**Comment by papitee** [comment]
hi.. the recent update is not adding hits from hit forker pls can you fix this
when trying to add hit from hit forker its say panda crazy not running

**Comment by JohnnyRS** [comment]
I just tested it and it seems to work for me. What url are you using for hit forker? this is what works for me: https://worker.mturk.com/?hit_forker
I am also testing it on hit forker version 1.2.4

**Comment by JohnnyRS** [comment]
Nevermind. I see what is happening. I only tested one button to see if it worked but after the first one no other buttons worked. I'll see if I can fix that today or tomorrow. Thanks for finding it. Need to check other external scripts if they do the same thing.

**Comment by JohnnyRS** [comment]
Got the hit forker buttons working in the version: 0.9.17
