### ISSUE TITLE
New Panda Adon 

### ISSUE THREAD

**Issue by JayblaqF8** [JohnnyRS/PandaCrazy-Max#22]
Hello,
The lastest update of Panda seems buggy
GOHAM wont last more than 7secs
Most HITs stops automatically
ETC
By the way, your work is really appreciated, thank you.

**Comment by JohnnyRS** [comment]
Thanks! Yes the GOHAM isn't supposed to do that when manually set. Need to fix it. But jobs automatically added from search jobs or externally starts off with GOHAM and will turn itself off after 7 seconds. Jobs manually collecting with the jobs button shouldn't stop unless there is a limit. Jobs automatically added by a search job or externally does have a duration time which it will stop. The automatic durations will have options later too.
But I will do a recheck of everything to make sure it's doing what it should be doing and rethink some of it.

**Comment by JohnnyRS** [comment]
GoHam duration should be fixed now when pressing the GoHam button. I did find some problems with jobs turning off when added externally which now has been fixed. Next update should be ready today or tomorrow.
