### ISSUE TITLE
Checkall checkbox Needed

### ISSUE THREAD

**Issue by IEagleeye** [JohnnyRS/PandaCrazy-Max#28]
![Need a checkall checkbox](https://user-images.githubusercontent.com/72181462/94768288-097e4e80-037d-11eb-9680-57a766bf6323.gif)

A checkall checkbox is needed in checking multiple non collecting pandas. Thank you

**Comment by JohnnyRS** [comment]
Thanks. That's a good idea. Will see what I can do in the next update.

**Comment by JohnnyRS** [comment]
The checkall button has been added and should work properly.
